<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1cpelf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1cpelf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA1cpelf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA1cpelf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA1cpelf\App_KernelDevDebugContainer([
    'container.build_hash' => 'A1cpelf',
    'container.build_id' => '7b7dea4d',
    'container.build_time' => 1736173756,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1cpelf');
