<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI30gtvx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI30gtvx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI30gtvx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI30gtvx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI30gtvx\App_KernelDevDebugContainer([
    'container.build_hash' => 'I30gtvx',
    'container.build_id' => '939697d1',
    'container.build_time' => 1736170346,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI30gtvx');
