<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7bkgs3n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7bkgs3n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7bkgs3n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7bkgs3n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7bkgs3n\App_KernelDevDebugContainer([
    'container.build_hash' => '7bkgs3n',
    'container.build_id' => 'f7b6cf7d',
    'container.build_time' => 1736180669,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7bkgs3n');
