_security_logout:
    resource: security.route_loader.logout
    type: service

app_find_user_id:
    path: /find-user-id
    controller: App\Controller\ImpersonateController::findUserId
    methods: [POST]
